[package]
name = "mech-core"
version = "0.0.5"
authors = ["Corey Montella <corey@mech-lang.org>"]
description = "The Mech language runtime. It's a small dataflow engine that accepts transactions of changes, and applies them to a compute network."
documentation = "http://docs.mech-lang.org"
homepage = "http://mech-lang.org"
repository = "https://github.com/mech-lang/core"
keywords = ["mech", "language", "programming", "dataflow", "runtime"]
categories = ["no-std", "science::robotics", "science", "game-engines", "database-implementations"]
license = "Apache-2.0"
readme = "README.md"

[badges]
gitlab = { repository = "mech-lang/core", branch = "master" }
maintenance = { status = "actively-developed" }

[features]
default = []
no-std = ["rlibc"]

[dependencies]
hashbrown = "0.9.1"
serde = {version = "1.0.105", default-features = false, features = ["alloc"] }
serde_derive = "1.0.105"
rlibc = { version = "=1.0", optional = true }
time = "0.2.15"
lazy_static = "1.4.0"
ahash = { version = "=0.3.5", default-features = false}

[dependencies.num-traits]
version = "0.2"
default-features = false
features = ["libm"]
