[package]
name = "mech"
version = "0.1.0"
authors = ["Corey Montella <cmontella@live.com>"]

[dependencies]
rlibc = "1.0"
hashmap_core = {git = "https://github.com/cmontella/hashmap_core.git"}

[dependencies.rand]
version = "0.4"
default-features = false