[package]
name = "mech-core"
version = "0.0.1"
authors = ["Corey Montella <corey@mech-lang.org>"]

[dependencies]
rlibc = "=1.0"
hashmap_core = "=0.1.8"

[dependencies.rand]
version = "=0.4"
default-features = false