[package]
name = "mech-core"
version = "0.0.1"
authors = ["Corey Montella <corey@mech-lang.org>"]
description = "The Mech language runtime. It's a small dataflow engine that accepts transactions of changes, and applies them to a compute network."
documentation = "http://mech-lang.org/page/learn/"
homepage = "http://mech-lang.org"
repository = "https://github.com/mech-lang/core"
keywords = ["mech", "language", "programming", "dataflow", "runtime"]
categories = ["no-std", "science::robotics", "science", "game-engines", "database-implementations"]
license = "Apache-2.0"
readme = "README.md"

[badges]
gitlab = { repository = "mech-lang/core", branch = "master" }
maintenance = { status = "actively-developed" }

[dependencies]
hashbrown = "0.1.8"
serde = {version = "1.0.46", default-features = false, features = ["alloc"] }
serde_derive = "1.0.46"
num = "0.2.0"
libm = "0.1.2"

[dependencies.rand]
version = "=0.4"
default-features = false

# no_std
#[dependencies.num]
#version = "0.2"
#default-features = false