[package]
name = "mech"
version = "0.1.0"
authors = ["Corey Montella <cmontella@live.com>"]

[dependencies]
rlibc = "1.0"
hashmap_core = "0.1.3"
time = "*"

[dependencies.rand]
version = "0.4"
default-features = false