[package]
name = "mech-core"
version = "0.0.5"
authors = ["Corey Montella <corey@mech-lang.org>"]
description = "The Mech language runtime. It's a small dataflow engine that accepts transactions of changes, and applies them to a compute network."
documentation = "http://docs.mech-lang.org"
homepage = "http://mech-lang.org"
repository = "https://github.com/mech-lang/core"
keywords = ["mech", "language", "programming", "dataflow", "runtime"]
categories = ["no-std", "science::robotics", "science", "game-engines", "database-implementations"]
license = "Apache-2.0"
readme = "README.md"
edition = "2021"

[badges]
gitlab = { repository = "mech-lang/core", branch = "main" }
maintenance = { status = "actively-developed" }

[features]
default = ["stdlib", "parallel"]
stdlib = ["time"]
parallel = ["rayon"]
no-std = ["rlibc"]

[dependencies]
hashbrown = "0.12.3"
serde = {version = "1.0.144", default-features = false, features = ["alloc"] }
serde_derive = "1.0.144"
rlibc = { version = "=1.0", optional = true }
lazy_static = "1.4.0"
seahash = "4.1.0"
indexmap = "1.9.1"
rayon = {version = "1.5.3", optional = true}
time = {version = "0.2.25", optional = true}

[dependencies.num-traits]
version = "0.2.15"
default-features = false
features = ["libm"]